"""Add quantity history relationship for item_id

Revision ID: 5934e747276a
Revises: 228bfc8477be
Create Date: 2021-03-03 15:07:07.632198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5934e747276a'
down_revision = '228bfc8477be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quantity_history', sa.Column('item_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'quantity_history', 'item', ['item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quantity_history', type_='foreignkey')
    op.drop_column('quantity_history', 'item_id')
    # ### end Alembic commands ###
