"""Initial migration

Revision ID: caf848544269
Revises: 
Create Date: 2021-03-06 17:37:52.318863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caf848544269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    category_table = op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    item_table = op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('quantity_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('old_quantity', sa.Integer(), nullable=True),
    sa.Column('new_quantity', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        category_table,
        [
            {'name': 'Books', 'description': 'Books and other printed publications'},
            {'name': 'Sporting goods', 'description': 'Goods for different kinds of sport, fitness, yoga and other '
                                                      'activities AND THERE GOES A LONG LONG LONG VERY LONG '
                                                      'DESCRIPTION AND SO ON AND ON JUST TO MAKE SURE THAT IT WILL BE '
                                                      'TRUNCATED'},
            {'name': 'Phones and accessories	', 'description': 'Phones, smartphones, tablets and accessories'},
            {'name': 'Cameras and photos	', 'description': 'Equipment for photo & video, accessories'},
            {'name': 'Musical instruments', 'description': 'Musical instruments and equipment for all levels'}
        ]
    )

    op.bulk_insert(
        item_table,
        [
            {
                'name': 'Ronald Reagan a Life in Photographs Cohen',
                'description': 'Ronald Reagan, a Life in Photographs David Elliot Cohen. Condition is "Like New". '
                               'Shipped with USPS Media Mail. In excellent shape',
                'price': 50,
                'quantity': 10,
                'image_url': '/static/images/item_images/1RonaldReagan.jpg',
                'category_id': 1
            },
            {
                'name': 'Team Lotus',
                'description': "This long-awaited memoir by a key figure in Formula 1 includes trenchant observations "
                               "on the 12 World Champions with whom he worked at Team Lotus.",
                'price': 40,
                'quantity': 20,
                'image_url': '/static/images/item_images/2TeamLotus.jpg',
                'category_id': 1
            },
            {
                'name': '2200 Meilen',
                'description': "Brand New: A new, unread, unused book in perfect condition with no missing or damaged "
                               "pages.",
                'price': 30,
                'quantity': 1,
                'image_url': '/static/images/item_images/32200Meilen.jpg',
                'category_id': 1
            },
            {
                'name': 'Quentin Blake',
                'description': "Quentin Blake is a collaboration between Tate and the House of Illustration, "
                               "published to coincide with the gallery's inaugural exhibition; Inside Stories, "
                               "a landmark show by Quentin Blake. ",
                'price': 40,
                'quantity': 20,
                'image_url': '/static/images/item_images/4QuentinBlake.jpg',
                'category_id': 1
            },
            {
                'name': 'A Struggle Through the Twentieth Century Holding',
                'description': "Author Jim Holding takes readers on a captivating trip down memory lane in his new "
                               "book, A Struggle Through the Twentieth Century. Now available from 1stBooks Library, "
                               "Barnes",
                'price': 30,
                'quantity': 10,
                'image_url': '/static/images/item_images/5AStruggle.jpg',
                'category_id': 1
            },
            {
                'name': 'Music of Time',
                'description': "A revelatory and deeply personal history of twentieth-century poetry by prize-winning "
                               "poet and memoirist John Burnside",
                'price': 40,
                'quantity': 5,
                'image_url': '/static/images/item_images/6MusicofTime.jpg',
                'category_id': 1
            },
            {
                'name': 'Oxford Illustrated History of the Renaissance',
                'description': "The story of the 'long Renaissance' for a new generation-from Giotto and Dante in "
                               "thirteenth-century Italy, to the English literary Renaissance in the first half of "
                               "the seventeenth century.",
                'price': 50,
                'quantity': 10,
                'image_url': '/static/images/item_images/7OxfordRenaissance.jpg',
                'category_id': 1
            },
            {
                'name': 'France: A History: from Gaul to de Gaulle',
                'description': "A witty history of 2000 years of French history from legendary popular historian John "
                               "Julius Norwich",
                'price': 30,
                'quantity': 5,
                'image_url': '/static/images/item_images/8France.jpg',
                'category_id': 1
            },
            {
                'name': 'The Homes We Build',
                'description': "The Homes We Build: A World of Houses and Habitats by Anne Jonas ",
                'price': 25,
                'quantity': 20,
                'image_url': '/static/images/item_images/9HomesWeBuild.jpg',
                'category_id': 1
            },
            {
                'name': 'The Wayward Leunig: Cartoons That Wandered Off',
                'description': "The Wayward Leunig is a superb companion volume to Michael Leunig's The Essential "
                               "Leunig, with ather 400 definitive cartoons spanning five decades. ",
                'price': 40,
                'quantity': 10,
                'image_url': '/static/images/item_images/10WaywardLeunig.jpg',
                'category_id': 1
            },
            {
                'name': 'Artful Noise: Percussion Literature',
                'description': "Twentieth-century composers created thousands of original works for solo percussion "
                               "and percussion ensemble. In this concise book, percussionist Thomas Siwe offers an "
                               "essential and much-needed survey of groundbreaking musical literature.",
                'price': 43.73,
                'quantity': 5,
                'image_url': '/static/images/item_images/11ArtfulNoise.jpg',
                'category_id': 1
            },
            {
                'name': 'The Art of Twentieth-Century American Poetry',
                'description': "Written by a leading critic, this invigorating introduction to modernist American "
                               "poetry conveys the excitement that can be generated by a careful reading of modernist"
                               " poems.",
                'price': 70.68,
                'quantity': 7,
                'image_url': '/static/images/item_images/12AmericanPoetry.jpg',
                'category_id': 1
            },
            {
                'name': 'Specialized Pitch 650b Mountain Bike',
                'description': "Size - XS Although the seat goes very high & has large wheels. Best Bike Brand, "
                               "Best Quality",
                'price': 599.99,
                'quantity': 3,
                'image_url': '/static/images/item_images/1Pitch650b.jpg',
                'category_id': 2
            },
            {
                'name': 'Yoga Circle',
                'description': "Yoga Circle Accessory Pilates Fitness Aerobics wheel body",
                'price': 30.40,
                'quantity': 20,
                'image_url': '/static/images/item_images/2YogaCircle.jpg',
                'category_id': 2
            },
            {
                'name': 'Yoga Mat',
                'description': "Yoga & Exercises Mat Thick Non-Slip Shock Absorbing Pad Exercise 72x24(inch) x 4mm",
                'price': 20.4,
                'quantity': 7,
                'image_url': '/static/images/item_images/3YogaMat.jpg',
                'category_id': 2
            },
            {
                'name': 'Pintail Longboard Cruiser Complete 46"',
                'description': "The pintail longboard is designed for beginners and recreational riders looking for "
                               "an easy introduction into the sport! The perfect sidewalk surfer. Comes in various "
                               "colors.",
                'price': 59.95,
                'quantity': 3,
                'image_url': '/static/images/item_images/4PintailLongboard.png',
                'category_id': 2
            },
            {
                'name': 'Wilson Ultra Comp Tennis Racket',
                'description': "Wilson Ultra Comp Tennis Racket 16 X 20 M53e. A perfect racket for a "
                               "beginner/intermediate player. It’s light and has great grip. "
                               "You cannot even tell the racket has been used before and comes with a bag to hold it",
                'price': 47.99,
                'quantity': 20,
                'image_url': '/static/images/item_images/5Wilson.jpg',
                'category_id': 2
            },
            {
                'name': 'Google Pixel 3a XL Smartphone 64GB',
                'description': "Experience high speeds for games, social media and other apps with this Google Pixel "
                               "3a XL smartphone. The 64GB of storage space offers plenty of room for apps, "
                               "photos and videos",
                'price': 409.95,
                'quantity': 20,
                'image_url': '/static/images/item_images/1GooglePixel3aXL.jpg',
                'category_id': 3
            },
            {
                'name': 'LG V50 ThinQ 5G - 128GB - Aurora Black',
                'description': "6 GB RAM, Storage Capacity 128 GB, Facial Recognition, Ultra Wide-Angle Camera, "
                               "OLED Display",
                'price': 189.99,
                'quantity': 30,
                'image_url': '/static/images/item_images/2LGV50ThinQ.jpg',
                'category_id': 3
            },
            {
                'name': 'Samsung Galaxy A20s',
                'description': "Samsung Galaxy A20s - 32GB-Black (without Simlock) (Dual Sim) NEW OVP invoice",
                'price': 184.99,
                'quantity': 15,
                'image_url': '/static/images/item_images/3SamsungGalaxyA20s.jpg',
                'category_id': 3
            },
            {
                'name': 'Huawei P30 Pro VOG-L29',
                'description': "Huawei P30 Pro 128GB Black Android Smartphone Handy ohne Vertrag 8GB RAM",
                'price': 186.00,
                'quantity': 23,
                'image_url': '/static/images/item_images/4HuaweiP30Pro.jpg',
                'category_id': 3
            },
            {
                'name': 'Apple iPhone 11 Pro Max',
                'description': "Dust-Resistant, Facial Recognition, Wide-Angle Camera, Fast Wireless Charging, "
                               "Ultra Wide-Angle Camera, OLED Display, Water-Resistant, HDR Display, Triple Rear "
                               " Super Retina Xdr Display, eSIM ",
                'price': 989.95,
                'quantity': 20,
                'image_url': '/static/images/item_images/5AppleiPhone11ProMax.jpg',
                'category_id': 3
            },
            {
                'name': 'Leica SL (Typ 601) Digital Mirrorless Camera Body',
                'description': "The camera is in proper working order; the viewfinder is clear, the sensor is "
                               "unmarked, and the memory card slots read & write. This camera includes a Leica "
                               "battery, battery charger, charging cables, USB cable, neck strap, front body cap, "
                               "and the original instructions & box. Please refer to the photos for details",
                'price': 1799,
                'quantity': 1,
                'image_url': '/static/images/item_images/1LeicaSL.jpg',
                'category_id': 4
            },
            {
                'name': 'Panasonic Lumix S1',
                'description': "Panasonic Lumix S1 24.2MP Mirrorless Digital Camera Body Pristine V-Log Body only. "
                               "Includes body cap, battery, charger, box, and all manuals",
                'price': 1325,
                'quantity': 3,
                'image_url': '/static/images/item_images/2Panasonic.jpg',
                'category_id': 4
            },
            {
                'name': 'Nikon Z 7II ',
                'description': "Nikon Z 7II 45.7MP Mirrorless Camera - Black. Bluetooth, Time Lapse, Tiltable Screen, "
                               "Red-Eye Reduction, Body Only, Touch Screen, Wi-Fi, 4K Video Recording, CMOS Sensor",
                'price': 3800,
                'quantity': 6,
                'image_url': '/static/images/item_images/3NikonZ7II.jpg',
                'category_id': 4
            },
            {
                'name': 'Canon EOS R5',
                'description': "Canon EOS R5 Digital Mirrorless Interchangeable Lens",
                'price': 3719,
                'quantity': 2,
                'image_url': '/static/images/item_images/4CanonR5.jpg',
                'category_id': 4
            },
            {
                'name': 'Fujifilm XH-1',
                'description': "Superb APS-C sensor camera for both still photography and video. 5-axis image "
                               "stabilized sensor and numerous electronic capabilities, including Fujifilm's industry "
                               "leading film-simulation modes. This was Fujifilm's top-of-the-line offering so is "
                               "fully loaded with options and capabilities.",
                'price': 798,
                'quantity': 4,
                'image_url': '/static/images/item_images/5FujifilmXH1.jpg',
                'category_id': 4
            },
            {
                'name': 'Electric Guitar Squier',
                'description': "Electric Guitar Squier by Fender Black Stratocaster Strat With Tremolo - Z90",
                'price': 155.99,
                'quantity': 3,
                'image_url': '/static/images/item_images/1Squier.jpg',
                'category_id': 5
            },
            {
                'name': 'Gibson',
                'description': "Gibson Songwriter Deluxe Studio",
                'price': 1849,
                'quantity': 2,
                'image_url': '/static/images/item_images/2Gibson.jpg',
                'category_id': 5
            },
            {
                'name': 'Yamaha Drum Set',
                'description': "Yamaha Stage Custom 8 Piece Drum Set/Shell Pack Cherry Wood Lacquer Kit",
                'price': 699.95,
                'quantity': 6,
                'image_url': '/static/images/item_images/3Yamaha.jpg',
                'category_id': 5
            },
            {
                'name': 'Violin',
                'description': "Old violin clear wood signed inside companion",
                'price': 159,
                'quantity': 1,
                'image_url': '/static/images/item_images/4Violin.jpg',
                'category_id': 5
            },
            {
                'name': 'STEINWAY & SONS piano',
                'description': "Outstanding STEINWAY & SONS 5'7 model M Grand Piano",
                'price': 1799,
                'quantity': 1,
                'image_url': '/static/images/item_images/5Steinway.jpg',
                'category_id': 5
            },{
                'name': 'French Horn',
                'description': "Pro New Anniversary 200 Copper Double French Horn Detachable Yellow Brass Bell",
                'price': 1639,
                'quantity': 2,
                'image_url': '/static/images/item_images/6FrenchHorn.jpg',
                'category_id': 5
            }
        ]
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quantity_history')
    op.drop_table('item')
    op.drop_table('user')
    op.drop_table('category')
    # ### end Alembic commands ###
